repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        exclude: "^.vscode/"
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
  - repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
      - id: committed
        stages: [commit-msg]
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.9
    hooks:
      - id: typos
        args: ["--diff", "--force-exclude"]
        exclude: "^.vscode/|go.mod|_test.go|^pkg/api/gen/proto/es"
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: go
        args: ["mod", "tidy"]
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-commit]
      - id: lint
        name: lint
        entry: make
        args: ["lint"]
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-commit]
      - id: build
        name: build
        entry: make
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-commit]
